In [15]:
from nba_api.stats.static import teams

nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

In [16]:
from nba_api.stats.endpoints import leaguegamefinder

# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22018,1610612738,BOS,Boston Celtics,0021800499,2018-12-25,BOS vs. PHI,W,265,121,...,0.850,13,42,55,21,8,4,9,21,7.0
1,22018,1610612738,BOS,Boston Celtics,0021800488,2018-12-23,BOS vs. CHA,W,240,119,...,0.800,11,36,47,30,8,4,14,22,16.0
2,22018,1610612738,BOS,Boston Celtics,0021800473,2018-12-21,BOS vs. MIL,L,241,107,...,0.750,9,27,36,22,13,3,5,16,-13.0
3,22018,1610612738,BOS,Boston Celtics,0021800458,2018-12-19,BOS vs. PHX,L,240,103,...,0.857,9,28,37,26,13,15,16,17,-8.0
4,22018,1610612738,BOS,Boston Celtics,0021800431,2018-12-15,BOS @ DET,L,240,104,...,0.739,12,32,44,19,11,4,14,25,-9.0

In [17]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count().loc['2015':]

           GAME_ID
SEASON_ID
2015           103
2016           115
2017           113
2018            43

In [18]:
# Subset the games to when the last 4 digits of SEASON_ID were 2017.
games_1718 = games[games.SEASON_ID.str[-4:] == '2017']
games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
43,42017,1610612738,BOS,Boston Celtics,0041700307,2018-05-27,BOS vs. CLE,L,240,79,...,0.737,11,31,42,18,6,0,5,20,-8.0
44,42017,1610612738,BOS,Boston Celtics,0041700306,2018-05-25,BOS @ CLE,L,241,99,...,0.550,5,26,31,25,5,2,13,18,-10.0
45,42017,1610612738,BOS,Boston Celtics,0041700305,2018-05-23,BOS vs. CLE,W,240,96,...,0.913,7,38,45,18,10,6,8,19,13.0
46,42017,1610612738,BOS,Boston Celtics,0041700304,2018-05-21,BOS @ CLE,L,239,102,...,0.767,9,28,37,21,9,3,9,26,-9.0
47,42017,1610612738,BOS,Boston Celtics,0041700303,2018-05-19,BOS @ CLE,L,240,86,...,0.786,6,28,34,16,4,4,15,25,-30.0

In [19]:
# Subset the games to where MATCHUP contains 'TOR'
raps_games_1718 = games_1718[games_1718.MATCHUP.str.contains('TOR')]
raps_games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
66,22017,1610612738,BOS,Boston Celtics,0021701171,2018-04-04,BOS @ TOR,L,237,78,...,0.893,8,35,43,10,7,3,16,16,-18.0
68,22017,1610612738,BOS,Boston Celtics,0021701140,2018-03-31,BOS vs. TOR,W,240,110,...,0.852,8,33,41,19,6,3,5,23,11.0
89,22017,1610612738,BOS,Boston Celtics,0021700798,2018-02-06,BOS @ TOR,L,240,91,...,0.750,9,29,38,21,3,3,17,19,-20.0
130,22017,1610612738,BOS,Boston Celtics,0021700188,2017-11-12,BOS vs. TOR,W,239,95,...,0.789,15,31,46,24,9,2,14,18,1.0

In [25]:
last_raps_game = raps_games_1718.sort_values('GAME_DATE').iloc[-2]
last_raps_game

SEASON_ID                     22017
TEAM_ID                  1610612738
TEAM_ABBREVIATION               BOS
TEAM_NAME            Boston Celtics
GAME_ID                  0021701140
GAME_DATE                2018-03-31
MATCHUP                 BOS vs. TOR
WL                                W
MIN                             240
PTS                             110
FGM                              40
FGA                              88
FG_PCT                        0.455
FG3M                              7
FG3A                             17
FG3_PCT                       0.412
FTM                              23
FTA                              27
FT_PCT                        0.852
OREB                              8
DREB                             33
REB                              41
AST                              19
STL                               6
BLK                               3
TOV                               5
PF                               23
PLUS_MINUS                       11
Name: 68, dtype: object

In [26]:
game_id = last_raps_game.GAME_ID
game_id

'0021701140'

In [8]:
# Get **all** the games so we can filter to an individual GAME_ID
result = leaguegamefinder.LeagueGameFinder()
all_games = result.get_data_frames()[0]
# Find the game_id we want
full_game = all_games[all_games.GAME_ID == game_id]
full_game

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
2656,22017,1610612738,BOS,Boston Celtics,0021701171,2018-04-04,BOS @ TOR,L,237,78,...,0.893,8,35,43,10,7,3,16,16,-18.0
2658,22017,1610612761,TOR,Toronto Raptors,0021701171,2018-04-04,TOR vs. BOS,W,240,96,...,0.750,12,36,48,23,10,6,10,25,18.0

In [9]:
import pandas as pd

def combine_team_games(df, keep_method='home'):
    '''Combine a TEAM_ID-GAME_ID unique table into rows by game. Slow.

        Parameters
        ----------
        df : Input DataFrame.
        keep_method : {'home', 'away', 'winner', 'loser', ``None``}, default 'home'
            - 'home' : Keep rows where TEAM_A is the home team.
            - 'away' : Keep rows where TEAM_A is the away team.
            - 'winner' : Keep rows where TEAM_A is the losing team.
            - 'loser' : Keep rows where TEAM_A is the winning team.
            - ``None`` : Keep all rows. Will result in an output DataFrame the same
                length as the input DataFrame.
                
        Returns
        -------
        result : DataFrame
    '''
    # Join every row to all others with the same game ID.
    joined = pd.merge(df, df, suffixes=['_A', '_B'],
                      on=['SEASON_ID', 'GAME_ID', 'GAME_DATE'])
    # Filter out any row that is joined to itself.
    result = joined[joined.TEAM_ID_A != joined.TEAM_ID_B]
    # Take action based on the keep_method flag.
    if keep_method is None:
        # Return all the rows.
        pass
    elif keep_method.lower() == 'home':
        # Keep rows where TEAM_A is the home team.
        result = result[result.MATCHUP_A.str.contains(' vs. ')]
    elif keep_method.lower() == 'away':
        # Keep rows where TEAM_A is the away team.
        result = result[result.MATCHUP_A.str.contains(' @ ')]
    elif keep_method.lower() == 'winner':
        result = result[result.WL_A == 'W']
    elif keep_method.lower() == 'loser':
        result = result[result.WL_A == 'L']
    else:
        raise ValueError(f'Invalid keep_method: {keep_method}')
    return result
    
# Combine the game rows into one. By default, the home team will be TEAM_A.
game_df = combine_team_games(full_game)
game_df

,SEASON_ID,TEAM_ID_A,TEAM_ABBREVIATION_A,TEAM_NAME_A,GAME_ID,GAME_DATE,MATCHUP_A,WL_A,MIN_A,PTS_A,...,FT_PCT_B,OREB_B,DREB_B,REB_B,AST_B,STL_B,BLK_B,TOV_B,PF_B,PLUS_MINUS_B
2,22017,1610612761,TOR,Toronto Raptors,0021701171,2018-04-04,TOR vs. BOS,W,240,96,...,0.893,8,35,43,10,7,3,16,16,-18.0

In [10]:
from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2(game_id)
pbp = pbp.get_data_frames()[0]
pbp.head()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION
0,0021701171,2,12,0,1,8:11 PM,12:00,None,None,None,...,None,None,None,0,0,None,NaN,None,None,None
1,0021701171,4,10,0,1,8:11 PM,12:00,Jump Ball Valanciunas vs. Baynes: Tip to Anunoby,None,None,...,Boston,Celtics,BOS,4,1628384,OG Anunoby,1.610613e+09,Toronto,Raptors,TOR
2,0021701171,7,2,1,1,8:11 PM,11:38,MISS DeRozan 21' Jump Shot,None,None,...,None,None,None,0,0,None,NaN,None,None,None
3,0021701171,8,4,0,1,8:11 PM,11:36,None,None,Tatum REBOUND (Off:0 Def:1),...,None,None,None,0,0,None,NaN,None,None,None
4,0021701171,9,2,86,1,8:12 PM,11:21,None,None,MISS Horford 12' Turnaround Fadeaway Shot,...,None,None,None,0,0,None,NaN,None,None,None