In [4]:
#First of all we have to write "conda install pandas" on Anaconda Prompt
#secondly we have to write "pip install nba_api" on Anaconda Prompt
#Team name : Duo of NBA

# Team members :

# Mustafa Demirman 201211018
# Burak Alım 201211301
# Title : NBA Data Analyst
 
 

# Data : From www.nba.com 

#Description : Getting team and player data from nba.com and  making analysis out of it about team and player performances.

#Goals : Detecting trendings about mainly teams and players from their win-lose ratio and win-lose strikes.

#Tools : Pandas,Matplotlib,requests,nba_api,msgpack,PyHamcrest
from nba_api.stats.static import teams

nba_teams = teams.get_teams()
# for example select the dictionary for the Celtics, which contains their team ID
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

In [5]:
from nba_api.stats.endpoints import leaguegamefinder

# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22018,1610612738,BOS,Boston Celtics,0021800431,2018-12-15,BOS @ DET,L,240,104,...,0.739,12,32,44,19,11,4,14,25,-9.0
1,22018,1610612738,BOS,Boston Celtics,0021800420,2018-12-14,BOS vs. ATL,W,241,129,...,0.900,13,34,47,28,15,9,21,21,21.0
2,22018,1610612738,BOS,Boston Celtics,0021800409,2018-12-12,BOS @ WAS,W,265,130,...,1.000,14,36,50,20,6,2,13,19,5.0
3,22018,1610612738,BOS,Boston Celtics,0021800393,2018-12-10,BOS vs. NOP,W,241,113,...,0.684,14,37,51,23,8,5,13,21,13.0
4,22018,1610612738,BOS,Boston Celtics,0021800383,2018-12-08,BOS @ CHI,W,238,133,...,0.733,13,41,54,34,10,4,7,14,56.0

In [6]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count().loc['2015':]

           GAME_ID
SEASON_ID
2015           103
2016           115
2017           113
2018            39

In [7]:
# Subset the games to when the last 4 digits of SEASON_ID was 2017.
games_1718 = games[games.SEASON_ID.str[-4:] == '2017']
games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
39,42017,1610612738,BOS,Boston Celtics,0041700307,2018-05-27,BOS vs. CLE,L,240,79,...,0.737,11,31,42,18,6,0,5,20,-8.0
40,42017,1610612738,BOS,Boston Celtics,0041700306,2018-05-25,BOS @ CLE,L,241,99,...,0.550,5,26,31,25,5,2,13,18,-10.0
41,42017,1610612738,BOS,Boston Celtics,0041700305,2018-05-23,BOS vs. CLE,W,240,96,...,0.913,7,38,45,18,10,6,8,19,13.0
42,42017,1610612738,BOS,Boston Celtics,0041700304,2018-05-21,BOS @ CLE,L,239,102,...,0.767,9,28,37,21,9,3,9,26,-9.0
43,42017,1610612738,BOS,Boston Celtics,0041700303,2018-05-19,BOS @ CLE,L,240,86,...,0.786,6,28,34,16,4,4,15,25,-30.0