# CENG 499 Special Topics in Computer Engineering TERM PROJECT



  Team Name : Duo of NBA
  
  
  
  Team Members and ID's : Mustafa Demirman 201211018
  
                     Burak AlÄ±m  201211301
             
             
  Title : NBA Data Analyst
  
  
  Last Edit Date : 10.01.2019

# Explanation of Project and Terms



  Data : From www.nba.com
  
  
  Description : Getting team and player data from nba.com and  making analysis out of it about team and player 
  performances.
  
  Goals : Detecting trendings about mainly teams and players from their win-lose ratio and win-lose strikes.
  
  Requirements : First of all we have to write "conda install pandas" on Anaconda Prompt and  we have to write "pip install
  nba_api" on Anaconda Prompt.  
  
  Tools :
  
  Pandas
  
  Matplotlib
  
  requests
  
  nba_api
  
  msgpack
  
  nba_api.stats.static

# Getting Team and Player IDs
The package also includes utilities for fetching player and team information available under nba_api.stats.static. We can use this to fetch player IDs and team IDs, which are often used as inputs to API endpoints.

In [33]:
from nba_api.stats.static import teams
# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
print('Number of teams fetched: {}'.format(len(nba_teams)))
nba_teams[:30]

Number of teams fetched: 30

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [41]:
from nba_api.stats.static import players
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
print('Number of players fetched: {}'.format(len(nba_players)))
nba_players[:99999]

Number of players fetched: 4374

[{'id': 76001,
  'full_name': 'Alaa Abdelnaby',
  'first_name': 'Alaa',
  'last_name': 'Abdelnaby'},
 {'id': 76002,
  'full_name': 'Zaid Abdul-Aziz',
  'first_name': 'Zaid',
  'last_name': 'Abdul-Aziz'},
 {'id': 76003,
  'full_name': 'Kareem Abdul-Jabbar',
  'first_name': 'Kareem',
  'last_name': 'Abdul-Jabbar'},
 {'id': 51,
  'full_name': 'Mahmoud Abdul-Rauf',
  'first_name': 'Mahmoud',
  'last_name': 'Abdul-Rauf'},
 {'id': 1505,
  'full_name': 'Tariq Abdul-Wahad',
  'first_name': 'Tariq',
  'last_name': 'Abdul-Wahad'},
 {'id': 949,
  'full_name': 'Shareef Abdur-Rahim',
  'first_name': 'Shareef',
  'last_name': 'Abdur-Rahim'},
 {'id': 76005,
  'full_name': 'Tom Abernethy',
  'first_name': 'Tom',
  'last_name': 'Abernethy'},
 {'id': 76006,
  'full_name': 'Forest Able',
  'first_name': 'Forest',
  'last_name': 'Able'},
 {'id': 76007,
  'full_name': 'John Abramovic',
  'first_name': 'John',
  'last_name': 'Abramovic'},
 {'id': 203518,
  'full_name': 'Alex Abrines',
  'first_name': 'Alex',
  'last_name': 'Abrines'},
 {'id': 101165,
  'full_name': 'Alex Acker',
  'first_name': 'Alex',
  'last_name': 'Acker'},
 {'id': 76008,
  'full_name': 'Donald Ackerman',
  'first_name': 'Donald',
  'last_name': 'Ackerman'},
 {'id': 76009,
  'full_name': 'Mark Acres',
  'first_name': 'Mark',
  'last_name': 'Acres'},
 {'id': 76010,
  'full_name': 'Charles Acton',
  'first_name': 'Charles',
  'last_name': 'Acton'},
 {'id': 203112,
  'full_name': 'Quincy Acy',
  'first_name': 'Quincy',
  'last_name': 'Acy'},
 {'id': 76011,
  'full_name': 'Alvan Adams',
  'first_name': 'Alvan',
  'last_name': 'Adams'},
 {'id': 76012,
  'full_name': 'Don Adams',
  'first_name': 'Don',
  'last_name': 'Adams'},
 {'id': 200801,
  'full_name': 'Hassan Adams',
  'first_name': 'Hassan',
  'last_name': 'Adams'},
 {'id': 1629121,
  'full_name': 'Jaylen Adams',
  'first_name': 'Jaylen',
  'last_name': 'Adams'},
 {'id': 203919,
  'full_name': 'Jordan Adams',
  'first_name': 'Jordan',
  'last_name': 'Adams'},
 {'id': 149,
  'full_name': 'Michael Adams',
  'first_name': 'Michael',
  'last_name': 'Adams'},
 {'id': 203500,
  'full_name': 'Steven Adams',
  'first_name': 'Steven',
  'last_name': 'Adams'},
 {'id': 912,
  'full_name': 'Rafael Addison',
  'first_name': 'Rafael',
  'last_name': 'Addison'},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo'},
 {'id': 76015,
  'full_name': 'Rick Adelman',
  'first_name': 'Rick',
  'last_name': 'Adelman'},
 {'id': 202399,
  'full_name': 'Jeff Adrien',
  'first_name': 'Jeff',
  'last_name': 'Adrien'},
 {'id': 201167,
  'full_name': 'Arron Afflalo',
  'first_name': 'Arron',
  'last_name': 'Afflalo'},
 {'id': 200772,
  'full_name': 'Maurice Ager',
  'first_name': 'Maurice',
  'last_name': 'Ager'},
 {'id': 76016,
  'full_name': 'Mark Aguirre',
  'first_name': 'Mark',
  'last_name': 'Aguirre'},
 {'id': 201336,
  'full_name': 'Blake Ahearn',
  'first_name': 'Blake',
  'last_name': 'Ahearn'},
 {'id': 76017,
  'full_name': 'Danny Ainge',
  'first_name': 'Danny',
  'last_name': 'Ainge'},
 {'id': 201582,
  'full_name': 'Alexis Ajinca',
  'first_name': 'Alexis',
  'last_name': 'Ajinca'},
 {'id': 76018,
  'full_name': 'Henry Akin',
  'first_name': 'Henry',
  'last_name': 'Akin'},
 {'id': 203006,
  'full_name': 'Josh Akognon',
  'first_name': 'Josh',
  'last_name': 'Akognon'},
 {'id': 1629152,
  'full_name': 'DeVaughn Akoon-Purcell',
  'first_name': 'DeVaughn',
  'last_name': 'Akoon-Purcell'},
 {'id': 202374,
  'full_name': 'Solomon Alabi',
  'first_name': 'Solomon',
  'last_name': 'Alabi'},
 {'id': 76019,
  'full_name': 'Mark Alarie',
  'first_name': 'Mark',
  'last_name': 'Alarie'},
 {'id': 76020,
  'full_name': 'Gary Alcorn',
  'first_name': 'Gary',
  'last_name': 'Alcorn'},
 {'id': 203128,
  'full_name': 'Furkan Aldemir',
  'first_name': 'Furkan',
  'last_name': 'Aldemir'},
 {'id': 202332,
  'full_name': 'Cole Aldrich',
  'first_name': 'Cole',
  'last_name': 'Aldrich'},
 {'id': 200746,
  'full_name': 'LaMarcus Aldridge',
  'first_name': 'LaMarcus',
  'last_name': 'Aldridge'},
 {'id': 76021,
  'full_name': 'Chuck Aleksinas',
  'first_name': 'Chuck',
  'last_name': 'Aleksinas'},
 {'id': 1626146,
  'full_name': 'Cliff Alexander',
  'first_name': 'Cliff',
  'last_name': 'Alexander'},
 {'id': 724,
  'full_name': 'Cory Alexander',
  'first_name': 'Cory',
  'last_name': 'Alexander'},
 {'id': 2042,
  'full_name': 'Courtney Alexander',
  'first_name': 'Courtney',
  'last_name': 'Alexander'},
 {'id': 76022,
  'full_name': 'Gary Alexander',
  'first_name': 'Gary',
  'last_name': 'Alexander'},
 {'id': 201570,
  'full_name': 'Joe Alexander',
  'first_name': 'Joe',
  'last_name': 'Alexander'},
 {'id': 2349,
  'full_name': 'Victor Alexander',
  'first_name': 'Victor',
  'last_name': 'Alexander'},
 {'id': 76024,
  'full_name': 'Steve Alford',
  'first_name': 'Steve',
  'last_name': 'Alford'},
 {'id': 76028,
  'full_name': 'Bob Allen',
  'first_name': 'Bob',
  'last_name': 'Allen'},
 {'id': 1628960,
  'full_name': 'Grayson Allen',
  'first_name': 'Grayson',
  'last_name': 'Allen'},
 {'id': 1628386,
  'full_name': 'Jarrett Allen',
  'first_name': 'Jarrett',
  'last_name': 'Allen'},
 {'id': 706,
  'full_name': 'Jerome Allen',
  'first_name': 'Jerome',
  'last_name': 'Allen'},
 {'id': 1628443,
  'full_name': 'Kadeem Allen',
  'first_name': 'Kadeem',
  'last_name': 'Allen'},
 {'id': 202730,
  'full_name': 'Lavoy Allen',
  'first_name': 'Lavoy',
  'last_name': 'Allen'},
 {'id': 76027,
  'full_name': 'Lucius Allen',
  'first_name': 'Lucius',
  'last_name': 'Allen'},
 {'id': 2124,
  'full_name': 'Malik Allen',
  'first_name': 'Malik',
  'last_name': 'Allen'},
 {'id': 76025,
  'full_name': 'Randy Allen',
  'first_name': 'Randy',
  'last_name': 'Allen'},
 {'id': 951,
  'full_name': 'Ray Allen',
  'first_name': 'Ray',
  'last_name': 'Allen'},
 {'id': 2754,
  'full_name': 'Tony Allen',
  'first_name': 'Tony',
  'last_name': 'Allen'},
 {'id': 76029,
  'full_name': 'Odis Allison',
  'first_name': 'Odis',
  'last_name': 'Allison'},
 {'id': 200984,
  'full_name': 'Lance Allred',
  'first_name': 'Lance',
  'last_name': 'Allred'},
 {'id': 76030,
  'full_name': 'Darrell Allums',
  'first_name': 'Darrell',
  'last_name': 'Allums'},
 {'id': 201165,
  'full_name': 'Morris Almond',
  'first_name': 'Morris',
  'last_name': 'Almond'},
 {'id': 308,
  'full_name': 'Derrick Alston',
  'first_name': 'Derrick',
  'last_name': 'Alston'},
 {'id': 1747,
  'full_name': 'Rafer Alston',
  'first_name': 'Rafer',
  'last_name': 'Alston'},
 {'id': 1824,
  'full_name': 'Peter Aluma',
  'first_name': 'Peter',
  'last_name': 'Aluma'},
 {'id': 680,
  'full_name': 'John Amaechi',
  'first_name': 'John',
  'last_name': 'Amaechi'},
 {'id': 732,
  'full_name': 'Ashraf Amaya',
  'first_name': 'Ashraf',
  'last_name': 'Amaya'},
 {'id': 202329,
  'full_name': 'Al-Farouq Aminu',
  'first_name': 'Al-Farouq',
  'last_name': 'Aminu'},
 {'id': 200811,
  'full_name': 'Lou Amundson',
  'first_name': 'Lou',
  'last_name': 'Amundson'},
 {'id': 76034,
  'full_name': 'Bob Anderegg',
  'first_name': 'Bob',
  'last_name': 'Anderegg'},
 {'id': 2365,
  'full_name': 'Chris Andersen',
  'first_name': 'Chris',
  'last_name': 'Andersen'},
 {'id': 2431,
  'full_name': 'David Andersen',
  'first_name': 'David',
  'last_name': 'Andersen'},
 {'id': 101187,
  'full_name': 'Alan Anderson',
  'first_name': 'Alan',
  'last_name': 'Anderson'},
 {'id': 202079,
  'full_name': 'Antonio Anderson',
  'first_name': 'Antonio',
  'last_name': 'Anderson'},
 {'id': 76035,
  'full_name': 'Cliff Anderson',
  'first_name': 'Cliff',
  'last_name': 'Anderson'},
 {'id': 76036,
  'full_name': 'Daniel Anderson',
  'first_name': 'Daniel',
  'last_name': 'Anderson'},
 {'id': 1507,
  'full_name': 'Derek Anderson',
  'first_name': 'Derek',
  'last_name': 'Anderson'},
 {'id': 76037,
  'full_name': 'Dwight Anderson',
  'first_name': 'Dwight',
  'last_name': 'Anderson'},
 {'id': 944,
  'full_name': 'Eric Anderson',
  'first_name': 'Eric',
  'last_name': 'Anderson'},
 {'id': 246,
  'full_name': 'Greg Anderson',
  'first_name': 'Greg',
  'last_name': 'Anderson'},
 {'id': 202341,
  'full_name': 'James Anderson',
  'first_name': 'James',
  'last_name': 'Anderson'},
 {'id': 76040,
  'full_name': 'Jerome Anderson',
  'first_name': 'Jerome',
  'last_name': 'Anderson'},
 {'id': 1626147,
  'full_name': 'Justin Anderson',
  'first_name': 'Justin',
  'last_name': 'Anderson'},
 {'id': 72,
  'full_name': 'Kenny Anderson',
  'first_name': 'Kenny',
  'last_name': 'Anderson'},
 {'id': 76041,
  'full_name': 'Kim Anderson',
  'first_name': 'Kim',
  'last_name': 'Anderson'},
 {'id': 203937,
  'full_name': 'Kyle Anderson',
  'first_name': 'Kyle',
  'last_name': 'Anderson'},
 {'id': 76042,
  'full_name': 'Michael Anderson',
  'first_name': 'Michael',
  'last_name': 'Anderson'},
 {'id': 76043,
  'full_name': 'Mitchell Anderson',
  'first_name': 'Mitchell',
  'last_name': 'Anderson'},
 {'id': 98,
  'full_name': 'Nick Anderson',
  'first_name': 'Nick',
  'last_name': 'Anderson'},
 {'id': 76045,
  'full_name': 'Richard Anderson',
  'first_name': 'Richard',
  'last_name': 'Anderson'},
 {'id': 76046,
  'full_name': 'Ron Anderson',
  'first_name': 'Ron',
  'last_name': 'Anderson'},
 {'id': 201583,
  'full_name': 'Ryan Anderson',
  'first_name': 'Ryan',
  'last_name': 'Anderson'},
 {'id': 1000,
  'full_name': 'Shandon Anderson',
  'first_name': 'Shandon',
  'last_name': 'Anderson'},
 {'id': 335,
  'full_name': 'Willie Anderson',
  'first_name': 'Willie',
  'last_name': 'Anderson'},
 {'id': 76048,
  'full_name': 'Wally Anderzunas',
  'first_name': 'Wally',
  'last_name': 'Anderzunas'},
 {'id': 101149,
  'full_name': 'Martynas Andriuskevicius',
  'first_name': 'Martynas',
  'last_name': 'Andriuskevicius'},
 {'id': 76049,
  'full_name': 'Don Anielak',
  'first_name': 'Don',
  'last_name': 'Anielak'},
 {'id': 1628387,
  'full_name': 'Ike Anigbogu',
  'first_name': 'Ike',
  'last_name': 'Anigbogu'},
 {'id': 76050,
  'full_name': 'Michael Ansley',
  'first_name': 'Michael',
  'last_name': 'Ansley'},
 {'id': 1512,
  'full_name': 'Chris Anstey',
  'first_name': 'Chris',
  'last_name': 'Anstey'},
 {'id': 203507,
  'full_name': 'Giannis Antetokounmpo',
  'first_name': 'Giannis',
  'last_name': 'Antetokounmpo'},
 {'id': 1628961,
  'full_name': 'Kostas Antetokounmpo',
  'first_name': 'Kostas',
  'last_name': 'Antetokounmpo'},
 {'id': 203648,
  'full_name': 'Thanasis Antetokounmpo',
  'first_name': 'Thanasis',
  'last_name': 'Antetokounmpo'},
 {'id': 2546,
  'full_name': 'Carmelo Anthony',
  'first_name': 'Carmelo',
  'last_name': 'Anthony'},
 {'id': 21,
  'full_name': 'Greg Anthony',
  'first_name': 'Greg',
  'last_name': 'Anthony'},
 {'id': 201202,
  'full_name': 'Joel Anthony',
  'first_name': 'Joel',
  'last_name': 'Anthony'},
 {'id': 203544,
  'full_name': 'Pero Antic',
  'first_name': 'Pero',
  'last_name': 'Antic'},
 {'id': 1628384,
  'full_name': 'OG Anunoby',
  'first_name': 'OG',
  'last_name': 'Anunoby'},
 {'id': 203951,
  'full_name': 'Keith Appling',
  'first_name': 'Keith',
  'last_name': 'Appling'},
 {'id': 2737,
  'full_name': 'Rafael Araujo',
  'first_name': 'Rafael',
  'last_name': 'Araujo'},
 {'id': 76053,
  'full_name': 'Stacey Arceneaux',
  'first_name': 'Stacey',
  'last_name': 'Arceneaux'},
 {'id': 76054,
  'full_name': 'Nate Archibald',
  'first_name': 'Nate',
  'last_name': 'Archibald'},
 {'id': 2425,
  'full_name': 'Robert Archibald',
  'first_name': 'Robert',
  'last_name': 'Archibald'},
 {'id': 1627853,
  'full_name': 'Ryan Arcidiacono',
  'first_name': 'Ryan',
  'last_name': 'Arcidiacono'},
 {'id': 76055,
  'full_name': 'Jim Ard',
  'first_name': 'Jim',
  'last_name': 'Ard'},
 {'id': 2240,
  'full_name': 'Gilbert Arenas',
  'first_name': 'Gilbert',
  'last_name': 'Arenas'},
 {'id': 2772,
  'full_name': 'Trevor Ariza',
  'first_name': 'Trevor',
  'last_name': 'Ariza'},
 {'id': 76056,
  'full_name': 'Paul Arizin',
  'first_name': 'Paul',
  'last_name': 'Arizin'},
 {'id': 76057,
  'full_name': 'Joe Arlauckas',
  'first_name': 'Joe',
  'last_name': 'Arlauckas'},
 {'id': 769,
  'full_name': 'B.J. Armstrong',
  'first_name': 'B.J.',
  'last_name': 'Armstrong'},
 {'id': 76061,
  'full_name': 'Bob Armstrong',
  'first_name': 'Bob',
  'last_name': 'Armstrong'},
 {'id': 2220,
  'full_name': 'Brandon Armstrong',
  'first_name': 'Brandon',
  'last_name': 'Armstrong'},
 {'id': 353,
  'full_name': 'Darrell Armstrong',
  'first_name': 'Darrell',
  'last_name': 'Armstrong'},
 {'id': 200756,
  'full_name': 'Hilton Armstrong',
  'first_name': 'Hilton',
  'last_name': 'Armstrong'},
 {'id': 76060,
  'full_name': 'Paul Armstrong',
  'first_name': 'Paul',
  'last_name': 'Armstrong'},
 {'id': 76059,
  'full_name': 'Tate Armstrong',
  'first_name': 'Tate',
  'last_name': 'Armstrong'},
 {'id': 76062,
  'full_name': 'Jesse Arnelle',
  'first_name': 'Jesse',
  'last_name': 'Arnelle'},
 {'id': 76063,
  'full_name': 'Jay Arnette',
  'first_name': 'Jay',
  'last_name': 'Arnette'},
 {'id': 76064,
  'full_name': 'Bob Arnzen',
  'first_name': 'Bob',
  'last_name': 'Arnzen'},
 {'id': 2306,
  'full_name': 'Carlos Arroyo',
  'first_name': 'Carlos',
  'last_name': 'Arroyo'},
 {'id': 201589,
  'full_name': 'Darrell Arthur',
  'first_name': 'Darrell',
  'last_name': 'Arthur'},
 {'id': 76065,
  'full_name': 'John Arthurs',
  'first_name': 'John',
  'last_name': 'Arthurs'},
 {'id': 1628503,
  'full_name': 'Jamel Artis',
  'first_name': 'Jamel',
  'last_name': 'Artis'},
 {'id': 201600,
  'full_name': 'Omer Asik',
  'first_name': 'Omer',
  'last_name': 'Asik'},
 {'id': 355,
  'full_name': 'Vincent Askew',
  'first_name': 'Vincent',
  'last_name': 'Askew'},
 {'id': 173,
  'full_name': 'Keith Askins',
  'first_name': 'Keith',
  'last_name': 'Askins'},
 {'id': 76068,
  'full_name': 'Don Asmonga',
  'first_name': 'Don',
  'last_name': 'Asmonga'},
 {'id': 76069,
  'full_name': 'Richard Atha',
  'first_name': 'Richard',
  'last_name': 'Atha'},
 {'id': 1088,
  'full_name': 'Chucky Atkins',
  'first_name': 'Chucky',
  'last_name': 'Atkins'},
 {'id': 76070,
  'full_name': 'Alvin Attles',
  'first_name': 'Alvin',
  'last_name': 'Attles'},
 {'id': 76071,
  'full_name': 'Chet Aubuchon',
  'first_name': 'Chet',
  'last_name': 'Aubuchon'},
 {'id': 278,
  'full_name': 'Stacey Augmon',
  'first_name': 'Stacey',
  'last_name': 'Augmon'},
 {'id': 201571,
  'full_name': 'D.J. Augustin',
  'first_name': 'D.J.',
  'last_name': 'Augustin'},
 {'id': 200788,
  'full_name': 'James Augustine',
  'first_name': 'James',
  'last_name': 'Augustine'},
 {'id': 1134,
  'full_name': 'Ike Austin',
  'first_name': 'Ike',
  'last_name': 'Austin'},
 {'id': 76073,
  'full_name': 'John Austin',
  'first_name': 'John',
  'last_name': 'Austin'},
 {'id': 76074,
  'full_name': 'Ken Austin',
  'first_name': 'Ken',
  'last_name': 'Austin'},
 {'id': 138,
  'full_name': 'Anthony Avent',
  'first_name': 'Anthony',
  'last_name': 'Avent'},
 {'id': 76076,
  'full_name': 'William Averitt',
  'first_name': 'William',
  'last_name': 'Averitt'},
 {'id': 1895,
  'full_name': 'William Avery',
  'first_name': 'William',
  'last_name': 'Avery'},
 {'id': 76078,
  'full_name': 'Dennis Awtrey',
  'first_name': 'Dennis',
  'last_name': 'Awtrey'},
 {'id': 202970,
  'full_name': 'Gustavo Ayon',
  'first_name': 'Gustavo',
  'last_name': 'Ayon'},
 {'id': 201965,
  'full_name': 'Jeff Ayres',
  'first_name': 'Jeff',
  'last_name': 'Ayres'},
 {'id': 1629028,
  'full_name': 'Deandre Ayton',
  'first_name': 'Deandre',
  'last_name': 'Ayton'},
 {'id': 101235,
  'full_name': 'Kelenna Azubuike',
  'first_name': 'Kelenna',
  'last_name': 'Azubuike'},
 {'id': 203569,
  'full_name': 'Chris Babb',
  'first_name': 'Chris',
  'last_name': 'Babb'},
 {'id': 202337,
  'full_name': 'Luke Babbitt',
  'first_name': 'Luke',
  'last_name': 'Babbitt'},
 {'id': 76079,
  'full_name': 'Milos Babic',
  'first_name': 'Milos',
  'last_name': 'Babic'},
 {'id': 76080,
  'full_name': 'Johnny Bach',
  'first_name': 'Johnny',
  'last_name': 'Bach'},
 {'id': 1628407,
  'full_name': 'Dwayne Bacon',
  'first_name': 'Dwayne',
  'last_name': 'Bacon'},
 {'id': 76081,
  'full_name': 'Jim Baechtold',
  'first_name': 'Jim',
  'last_name': 'Baechtold'},
 {'id': 2053,
  'full_name': 'Dalibor Bagaric',
  'first_name': 'Dalibor',
  'last_name': 'Bagaric'},
 {'id': 76082,
  'full_name': 'John Bagley',
  'first_name': 'John',
  'last_name': 'Bagley'},
 {'id': 1628963,
  'full_name': 'Marvin Bagley III',
  'first_name': 'Marvin',
  'last_name': 'Bagley III'},
 {'id': 76084,
  'full_name': 'Carl Bailey',
  'first_name': 'Carl',
  'last_name': 'Bailey'},
 {'id': 76083,
  'full_name': 'Gus Bailey',
  'first_name': 'Gus',
  'last_name': 'Bailey'},
 {'id': 76085,
  'full_name': 'James Bailey',
  'first_name': 'James',
  'last_name': 'Bailey'},
 {'id': 1847,
  'full_name': 'Thurl Bailey',
  'first_name': 'Thurl',
  'last_name': 'Bailey'},
 {'id': 1753,
  'full_name': 'Toby Bailey',
  'first_name': 'Toby',
  'last_name': 'Bailey'},
 {'id': 203946,
  'full_name': 'Cameron Bairstow',
  'first_name': 'Cameron',
  'last_name': 'Bairstow'},
 {'id': 1858,
  'full_name': 'Mark Baker',
  'first_name': 'Mark',
  'last_name': 'Baker'},
 {'id': 2486,
  'full_name': 'Maurice Baker',
  'first_name': 'Maurice',
  'last_name': 'Baker'},
 {'id': 76089,
  'full_name': 'Norm Baker',
  'first_name': 'Norm',
  'last_name': 'Baker'},
 {'id': 1627758,
  'full_name': 'Ron Baker',
  'first_name': 'Ron',
  'last_name': 'Baker'},
 {'id': 452,
  'full_name': 'Vin Baker',
  'first_name': 'Vin',
  'last_name': 'Baker'},
 {'id': 1627735,
  'full_name': 'Wade Baldwin IV',
  'first_name': 'Wade',
  'last_name': 'Baldwin IV'},
 {'id': 200764,
  'full_name': 'Renaldo Balkman',
  'first_name': 'Renaldo',
  'last_name': 'Balkman'},
 {'id': 76090,
  'full_name': 'Cedric Ball',
  'first_name': 'Cedric',
  'last_name': 'Ball'},
 {'id': 1628366,
  'full_name': 'Lonzo Ball',
  'first_name': 'Lonzo',
  'last_name': 'Ball'},
 {'id': 76091,
  'full_name': 'Greg Ballard',
  'first_name': 'Greg',
  'last_name': 'Ballard'},
 {'id': 76092,
  'full_name': 'Herschel Baltimore',
  'first_name': 'Herschel',
  'last_name': 'Baltimore'},
 {'id': 1628964,
  'full_name': 'Mohamed Bamba',
  'first_name': 'Mohamed',
  'last_name': 'Bamba'},
 {'id': 76093,
  'full_name': 'Gene Banks',
  'first_name': 'Gene',
  'last_name': 'Banks'},
 {'id': 2556,
  'full_name': 'Marcus Banks',
  'first_name': 'Marcus',
  'last_name': 'Banks'},
 {'id': 76094,
  'full_name': 'Ken Bannister',
  'first_name': 'Ken',
  'last_name': 'Bannister'},
 {'id': 76095,
  'full_name': 'Mike Bantom',
  'first_name': 'Mike',
  'last_name': 'Bantom'},
 {'id': 76096,
  'full_name': 'John Barber',
  'first_name': 'John',
  'last_name': 'Barber'},
 {'id': 2571,
  'full_name': 'Leandro Barbosa',
  'first_name': 'Leandro',
  'last_name': 'Barbosa'},
 {'id': 76097,
  'full_name': 'Stephen Bardo',
  'first_name': 'Stephen',
  'last_name': 'Bardo'},
 {'id': 200826,
  'full_name': 'J.J. Barea',
  'first_name': 'J.J.',
  'last_name': 'Barea'},
 {'id': 200745,
  'full_name': 'Andrea Bargnani',
  'first_name': 'Andrea',
  'last_name': 'Bargnani'},
 {'id': 76098,
  'full_name': 'Cliff Barker',
  'first_name': 'Cliff',
  'last_name': 'Barker'},
 {'id': 76099,
  'full_name': 'Tom Barker',
  'first_name': 'Tom',
  'last_name': 'Barker'},
 {'id': 787,
  'full_name': 'Charles Barkley',
  'first_name': 'Charles',
  'last_name': 'Barkley'},
 {'id': 2057,
  'full_name': 'Erick Barkley',
  'first_name': 'Erick',
  'last_name': 'Barkley'},
 {'id': 76102,
  'full_name': 'Don Barksdale',
  'first_name': 'Don',
  'last_name': 'Barksdale'},
 {'id': 203084,
  'full_name': 'Harrison Barnes',
  'first_name': 'Harrison',
  'last_name': 'Barnes'},
 {'id': 76103,
  'full_name': 'Harry Barnes',
  'first_name': 'Harry',
  'last_name': 'Barnes'},
 {'id': 76105,
  'full_name': 'Jim Barnes',
  'first_name': 'Jim',
  'last_name': 'Barnes'},
 {'id': 76104,
  'full_name': 'Marvin Barnes',
  'first_name': 'Marvin',

In [61]:
fundamental = [player for player in nba_players
                   if player['full_name'] == 'LeBron James'][0]
fundamental
#We can find only one player information typing full name.

{'id': 2544,
 'full_name': 'LeBron James',
 'first_name': 'LeBron',
 'last_name': 'James'}

In [59]:
from nba_api.stats.endpoints import playercareerstats
# Lebron James's career.We use playercareerstats fucntion and we have to write player_id what we found above.
career = playercareerstats.PlayerCareerStats(player_id='2544')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,34,34,1178.0,340,...,0.682,32,251,283,243,44,24,116,54,928

In [52]:
from nba_api.stats.endpoints import commonplayerinfo

player_info = commonplayerinfo.CommonPlayerInfo(player_id=2544)

In [58]:
# Returns the raw response of the request.
player_info.get_response()

# Returns all data in a JSON string.
player_info.get_json()

# Returns all data in a dictionary.
player_info.get_dict()

# Returns all data in a normalized JSON string.
player_info.get_normalized_json()

# Returns all data in a normalized dictionary.
player_info.get_normalized_dict()
# Returns a list of all data in a pandas DataFrame structure.
player_info.get_data_frames()

[   PERSON_ID FIRST_NAME LAST_NAME DISPLAY_FIRST_LAST DISPLAY_LAST_COMMA_FIRST  \
 0       2544     LeBron     James       LeBron James            James, LeBron

   DISPLAY_FI_LAST            BIRTHDATE                        SCHOOL COUNTRY  \
 0        L. James  1984-12-30T00:00:00  St. Vincent-St. Mary HS (OH)     USA

                    LAST_AFFILIATION     ...         TEAM_CITY    PLAYERCODE  \
 0  St. Vincent-St. Mary HS (OH)/USA     ...       Los Angeles  lebron_james

    FROM_YEAR TO_YEAR DLEAGUE_FLAG NBA_FLAG  GAMES_PLAYED_FLAG DRAFT_YEAR  \
 0       2003    2018            N        Y                  Y       2003

   DRAFT_ROUND DRAFT_NUMBER
 0           1            1

 [1 rows x 30 columns],
    PLAYER_ID   PLAYER_NAME TimeFrame   PTS  AST  REB    PIE
 0       2544  LeBron James   2018-19  27.3  7.1  8.3  0.196,
    SEASON_ID
 0      12003
 1      22003
 2      12004
 3      22004
 4      32004
 5      12005
 6      22005
 7      32005
 8      42005
 9      12006
 10     22006
 11     32006
 12     42006
 13     12007
 14     22007
 15     32007
 16     42007
 17     12008
 18     22008
 19     32008
 20     42008
 21     12009
 22     22009
 23     32009
 24     42009
 25     12010
 26     22010
 27     32010
 28     42010
 29     12011
 30     22011
 31     32011
 32     42011
 33     12012
 34     22012
 35     32012
 36     42012
 37     12013
 38     22013
 39     32013
 40     42013
 41     12014
 42     22014
 43     32014
 44     42014
 45     12015
 46     22015
 47     32015
 48     42015
 49     12016
 50     22016
 51     32016
 52     42016
 53     12017
 54     22017
 55     32017
 56     42017
 57     12018
 58     22018]

# Finding Games
To find a single game, use the LeagueGameFinder class. While you can call it without any arguments and get nearly 30,000 games returned across the NBA, WNBA, G-League, and international ball

# Get All Celtics Games

In [ ]:
# from nba_api.stats.static import teams

nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

In [16]:
from nba_api.stats.endpoints import leaguegamefinder

# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22018,1610612738,BOS,Boston Celtics,0021800499,2018-12-25,BOS vs. PHI,W,265,121,...,0.850,13,42,55,21,8,4,9,21,7.0
1,22018,1610612738,BOS,Boston Celtics,0021800488,2018-12-23,BOS vs. CHA,W,240,119,...,0.800,11,36,47,30,8,4,14,22,16.0
2,22018,1610612738,BOS,Boston Celtics,0021800473,2018-12-21,BOS vs. MIL,L,241,107,...,0.750,9,27,36,22,13,3,5,16,-13.0
3,22018,1610612738,BOS,Boston Celtics,0021800458,2018-12-19,BOS vs. PHX,L,240,103,...,0.857,9,28,37,26,13,15,16,17,-8.0
4,22018,1610612738,BOS,Boston Celtics,0021800431,2018-12-15,BOS @ DET,L,240,104,...,0.739,12,32,44,19,11,4,14,25,-9.0

# Filter to Games in the 2017-18 Season

In [18]:
# Subset the games to when the last 4 digits of SEASON_ID were 2017.
games_1718 = games[games.SEASON_ID.str[-4:] == '2017']
games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
43,42017,1610612738,BOS,Boston Celtics,0041700307,2018-05-27,BOS vs. CLE,L,240,79,...,0.737,11,31,42,18,6,0,5,20,-8.0
44,42017,1610612738,BOS,Boston Celtics,0041700306,2018-05-25,BOS @ CLE,L,241,99,...,0.550,5,26,31,25,5,2,13,18,-10.0
45,42017,1610612738,BOS,Boston Celtics,0041700305,2018-05-23,BOS vs. CLE,W,240,96,...,0.913,7,38,45,18,10,6,8,19,13.0
46,42017,1610612738,BOS,Boston Celtics,0041700304,2018-05-21,BOS @ CLE,L,239,102,...,0.767,9,28,37,21,9,3,9,26,-9.0
47,42017,1610612738,BOS,Boston Celtics,0041700303,2018-05-19,BOS @ CLE,L,240,86,...,0.786,6,28,34,16,4,4,15,25,-30.0

In [17]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count().loc['2015':]
#Number of matches played by Boston Celtics since 2015

           GAME_ID
SEASON_ID
2015           103
2016           115
2017           113
2018            43

# Filter to Games Against the Raptors

In [19]:
# Subset the games to where MATCHUP contains 'TOR'
raps_games_1718 = games_1718[games_1718.MATCHUP.str.contains('TOR')]
raps_games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
66,22017,1610612738,BOS,Boston Celtics,0021701171,2018-04-04,BOS @ TOR,L,237,78,...,0.893,8,35,43,10,7,3,16,16,-18.0
68,22017,1610612738,BOS,Boston Celtics,0021701140,2018-03-31,BOS vs. TOR,W,240,110,...,0.852,8,33,41,19,6,3,5,23,11.0
89,22017,1610612738,BOS,Boston Celtics,0021700798,2018-02-06,BOS @ TOR,L,240,91,...,0.750,9,29,38,21,3,3,17,19,-20.0
130,22017,1610612738,BOS,Boston Celtics,0021700188,2017-11-12,BOS vs. TOR,W,239,95,...,0.789,15,31,46,24,9,2,14,18,1.0

# Sort by Game Date and Select the Last Row

In [25]:
last_raps_game = raps_games_1718.sort_values('GAME_DATE').iloc[-2]
last_raps_game

SEASON_ID                     22017
TEAM_ID                  1610612738
TEAM_ABBREVIATION               BOS
TEAM_NAME            Boston Celtics
GAME_ID                  0021701140
GAME_DATE                2018-03-31
MATCHUP                 BOS vs. TOR
WL                                W
MIN                             240
PTS                             110
FGM                              40
FGA                              88
FG_PCT                        0.455
FG3M                              7
FG3A                             17
FG3_PCT                       0.412
FTM                              23
FTA                              27
FT_PCT                        0.852
OREB                              8
DREB                             33
REB                              41
AST                              19
STL                               6
BLK                               3
TOV                               5
PF                               23
PLUS_MINUS                       11
Name: 68, dtype: object

In [26]:
game_id = last_raps_game.GAME_ID
game_id

'0021701140'

In [8]:
# Get **all** the games so we can filter to an individual GAME_ID
result = leaguegamefinder.LeagueGameFinder()
all_games = result.get_data_frames()[0]
# Find the game_id we want
full_game = all_games[all_games.GAME_ID == game_id]
full_game

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
2656,22017,1610612738,BOS,Boston Celtics,0021701171,2018-04-04,BOS @ TOR,L,237,78,...,0.893,8,35,43,10,7,3,16,16,-18.0
2658,22017,1610612761,TOR,Toronto Raptors,0021701171,2018-04-04,TOR vs. BOS,W,240,96,...,0.750,12,36,48,23,10,6,10,25,18.0

In [9]:
import pandas as pd

def combine_team_games(df, keep_method='home'):
    '''TEAM_ID-GAME_ID'yi benzersiz bir tablo olarak oyuna gÃ¶re sÄ±ralayacaÄÄ±z.

        Parametreler
        ----------
        df : Input DataFrame.
        keep_method : {'home', 'away', 'winner', 'loser', ``None``}, default 'home'
            - 'home' : Keep rows where TEAM_A is the home team.
            - 'away' : Keep rows where TEAM_A is the away team.
            - 'winner' : Keep rows where TEAM_A is the losing team.
            - 'loser' : Keep rows where TEAM_A is the winning team.
            - ``None`` : Keep all rows. will result in an output DataFrame the same
                length as the input DataFrame.
                
        Returns
        -------
        result : DataFrame
    '''
    # Join every row to all others with the same game ID.
    joined = pd.merge(df, df, suffixes=['_A', '_B'],
                      on=['SEASON_ID', 'GAME_ID', 'GAME_DATE'])
    # Filter out any row that is joined to itself.
    result = joined[joined.TEAM_ID_A != joined.TEAM_ID_B]
    # Take action based on the keep_method flag.
    if keep_method is None:
        # Return all the rows.
        pass
    elif keep_method.lower() == 'home':
        # Keep rows where TEAM_A is the home team.
        result = result[result.MATCHUP_A.str.contains(' vs. ')]
    elif keep_method.lower() == 'away':
        # Keep rows where TEAM_A is the away team.
        result = result[result.MATCHUP_A.str.contains(' @ ')]
    elif keep_method.lower() == 'winner':
        result = result[result.WL_A == 'W']
    elif keep_method.lower() == 'loser':
        result = result[result.WL_A == 'L']
    else:
        raise ValueError(f'Invalid keep_method: {keep_method}')
    return result
    
# Combine the game rows into one. By default, the home team will be TEAM_A.
game_df = combine_team_games(full_game)
game_df

,SEASON_ID,TEAM_ID_A,TEAM_ABBREVIATION_A,TEAM_NAME_A,GAME_ID,GAME_DATE,MATCHUP_A,WL_A,MIN_A,PTS_A,...,FT_PCT_B,OREB_B,DREB_B,REB_B,AST_B,STL_B,BLK_B,TOV_B,PF_B,PLUS_MINUS_B
2,22017,1610612761,TOR,Toronto Raptors,0021701171,2018-04-04,TOR vs. BOS,W,240,96,...,0.893,8,35,43,10,7,3,16,16,-18.0

# Play-by-play Data for a Given Game

In [10]:
from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2(game_id)
pbp = pbp.get_data_frames()[0]
pbp.head()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION
0,0021701171,2,12,0,1,8:11 PM,12:00,None,None,None,...,None,None,None,0,0,None,NaN,None,None,None
1,0021701171,4,10,0,1,8:11 PM,12:00,Jump Ball Valanciunas vs. Baynes: Tip to Anunoby,None,None,...,Boston,Celtics,BOS,4,1628384,OG Anunoby,1.610613e+09,Toronto,Raptors,TOR
2,0021701171,7,2,1,1,8:11 PM,11:38,MISS DeRozan 21' Jump Shot,None,None,...,None,None,None,0,0,None,NaN,None,None,None
3,0021701171,8,4,0,1,8:11 PM,11:36,None,None,Tatum REBOUND (Off:0 Def:1),...,None,None,None,0,0,None,NaN,None,None,None
4,0021701171,9,2,86,1,8:12 PM,11:21,None,None,MISS Horford 12' Turnaround Fadeaway Shot,...,None,None,None,0,0,None,NaN,None,None,None